### PR TITLE
Add exit status

### PR DESCRIPTION
**Pull request by TerryRPatterson**
Hello @ayosec,
This is an initial draft, add access to the last exit status(`$?`).
I wanted to see if you are interested in accepting the change before polishing it.

Also I was not sure if variables was the right place to put the new function, but it felt like it made the most sense.

### CODE REVIEW

**Comment by ayosec** [comment]
> I wanted to see if you are interested in accepting the change before polishing it.

Yes, I think that the value of `$?` can be useful for builtins. Thanks for the patch!

Regarding implementation, do you think it makes sense to return an instance of [`std::process::ExitStatus`](https://doc.rust-lang.org/stable/std/process/struct.ExitStatus.html), which can be created with [`ExitStatusExt.from_raw`](https://doc.rust-lang.org/stable/std/os/unix/process/trait.ExitStatusExt.html#tymethod.from_raw), instead of the raw value?

**Comment by TerryRPatterson** [comment]
I think it is ready for review.
At the moment it only supports, unix.
Window's [ExitStatusExt](https://doc.rust-lang.org/std/os/windows/process/trait.ExitStatusExt.html) take a `u32` instead of an `i32`.

Do you want windows support? (Does windows even have a normal bash?)
I think it can  be done using `i31::to_be_bytes` and `u32::from_be_bytes`, but I can't test it.

**Comment by ayosec** [comment]
It looks good.

I wrote a small builtin to test it:

```rust
impl Builtin for Status {
    fn call(&mut self, args: &mut Args) -> Result<()> {
        args.no_options()?;

        let status = variables::get_last_exit_status();
        println!("code = {:?}  signal = {:?}", status.code(), status.signal());

        Ok(())
    }
}
```

And everything seems to work:

```console
$ enable -f target/debug/examples/libstatus.so status

$ : ; status
code = Some(0)  signal = None

$ ruby -e 'Process.kill "KILL", $$' ; status
Killed
code = None  signal = Some(9)
```

Thanks for the patch!

> Do you want windows support?

Not really. I guess that most people on Windows are using [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux) if they need or want to use bash, so I don't think it's worth it to support it.

**Comment by ayosec** [comment]
I published the version 0.3.1 with this patch.

**Pull request merged**
